### ISSUE TITLE
Get user details in payload

### ISSUE THREAD

**Issue by btechgroup** [smartprocure/react-social-auth#2]
Hi,

how I can get the user details in payload while signing in with linkedin?

Regards,
Owais

**Comment by daedalus28** [comment]
Everything is passed as part of the payload to the onSuccess function. If you think there's more info we can pass along, you are welcome to submit a PR to add more stuff. The relevant lines are here:

**Comment by daedalus28** [comment]
Closing this since I think it's resolved. If I've misunderstood, feel free to reopen.
